#!/usr/bin/env python3
import sys
import argparse
import random

parser = argparse.ArgumentParser(description = "Generate an uncrackable password!")
# adds all of the arguments to our parser for the user's command line prompt
parser.add_argument('-w', '--words', metavar = "WORDS", type = int, default = 4, help = "amount of words (Default: 4)")
parser.add_argument('-c', '--caps', metavar = "CAPS", type = int, default = 0, help = "capitalizes front of this amount of numbers (Default: 0)")
parser.add_argument('-n', '--numbers', metavar = "NUMBERS", type = int, default = 0, help = "amount of places to add random numbers (Default: 0)")
parser.add_argument('-s', '--symbols', metavar = "SYMBOLS", type = int, default = 0, help = "amount of places to add random symbols (Default: 0)")

args = parser.parse_args()

words = args.words

if words <= 0:
    words = 1

caps = args.caps

if caps <= 0:
    caps = 0

if caps >= words:
    caps = words

numbers = args.numbers

if numbers <= 0:
    numbers = 0

symbols = args.symbols

if symbols <= 0:
    symbols = 0

dictionary = open("words.txt", 'r')
pieces = []
symbols_list = ["!", "@", "#", "$", "%", "^", "&", "*", "-", "+", "<", ">", "?"]

def random_line(dictionary):
    lines = open(dictionary).read().splitlines()
    random_word = (random.choice(lines))
    return random_word.lower()

for x in range(0, words):
    pieces.append(random_line('words.txt'))

for c in range(0, caps):
    random_element = random.randint(0, words - 1)
    pieces[random_element] = pieces[random_element].capitalize()

for y in range(0, numbers):
    random_number = str(random.randint(0,9999))
    pieces[random.randint(0, words - 1)] += random_number

for z in range(0, symbols):
    random_symbol = random.choice(symbols_list)
    pieces[random.randint(0, words - 1)] += random_symbol

print("".join(pieces))
